In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("sharks_df.csv")

In [4]:
df.head(10)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,24th May,2026.0,Unprovoked,Australia,Queensland,Kennedy Shoal,Spearfishing,Michael Jensz,M,39,...,Undetermined Bull shark most likely,Simon de Marchi: 9 News: 7 News: ABC News:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17th May,2026.0,Questionable,USA,Maryland,Assateague State Park,Surfing,Brendan Oster,M,?,...,Blue fish bite most probable,Keithe Cowley: Delmarva Now:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16th May,2026.0,Unprovoked,Australia,Western Australia,Horseshoe Reef Rottnest Island,Skindiving,Steven Mattaboni,M,38,...,Great White Shark,ABC News: 9 News: 7 News: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,14th April,2026.0,UNprovoked,Maldives,Gaafu Alif Atoll,Kooddoo,Swimming,Not stated - on honeymoon,M,?,...,Unknown,The U.S. Sun: Simon De Marchi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3rd April,2026.0,Unprovoked,Australia,South Australia,Middleton Beach Fleurieu Peninsula Adelaide,Surfing,Oliver Tokic-Bensley,M,16,...,Bronze Whaler,ABC News: The Guardian: Andrew Currie and Bob...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,26th March,2026.0,Unprovoked,Bahamas,Andros Island,Fresh Creek,Swimming,Australian woman,F,22,...,Unknown,WIC News: Melissa Michaelson,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,25th March,2026.0,Unprovoked,Australia,South Australia,Cape Jaffa Limestone Coast,Diving,Luke Kuhn,M,?,...,Great White Shark 3.5m (11.5ft),Bob Myatt GSAF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,22nd-23rd March,2026.0,Unprovoked,Australia,NSW,Little Avalon Beach,Surfing,Unknown,M,30+,...,Unknown,Melissa Michaelson: Instagram,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,...,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,...,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(7090, 23)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7090 entries, 0 to 7089
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7090 non-null   object
 1   Year            7088 non-null   float64
 2   Type            7072 non-null   object
 3   Country         7040 non-null   object
 4   State           6603 non-null   object
 5   Location        6523 non-null   object
 6   Activity        6507 non-null   object
 7   Name            6872 non-null   object
 8   Sex             6512 non-null   object
 9   Age             4096 non-null   object
 10  Injury          7054 non-null   object
 11  Fatal Y/N       6529 non-null   object
 12  Time            3563 non-null   object
 13  Species         3959 non-null   object
 14  Source          7070 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   object
 17  href            6796 non-null   object
 18  Case Number     6798 non-null   object
 19  Case Number.1   6797 non-null   object
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      object
 22  Unnamed: 22     2 non-null      object
dtypes: float64(2), object(21)
memory usage: 1.2+ MB

In [7]:
df.nunique().sort_values(ascending=False)

original order    6797
pdf               6789
href formula      6784
Case Number       6777
href              6776
Case Number.1     6775
Date              6098
Name              5804
Source            5415
Location          4634
Injury            4200
Species           1748
Activity          1612
State              948
Time               478
Year               261
Country            253
Age                178
Type                14
Fatal Y/N           12
Sex                 11
Unnamed: 22          2
Unnamed: 21          1
dtype: int64

In [8]:
missing = df.isna().mean().mul(100).sort_values(ascending=False)
missing

Unnamed: 21       99.985896
Unnamed: 22       99.971791
Time              49.746121
Species           44.160790
Age               42.228491
Activity           8.222849
Sex                8.152327
Location           7.997179
Fatal Y/N          7.912553
State              6.868829
href formula       4.174894
href               4.146685
Case Number.1      4.132581
Case Number        4.118477
pdf                4.104372
original order     4.104372
Name               3.074753
Country            0.705219
Injury             0.507757
Source             0.282087
Type               0.253879
Year               0.028209
Date               0.000000
dtype: float64

In [24]:
df.describe()

              Year  original order
count  7088.000000     6799.000000
mean   1936.208521     3401.152081
std     270.400387     1963.076319
min       0.000000        2.000000
25%    1948.000000     1701.500000
50%    1987.000000     3401.000000
75%    2010.000000     5100.500000
max    2026.000000     6802.000000

In [42]:
df.describe(include="object")

,Date,Type,Country,State,Location,Activity,Name,Sex,Age,Injury,...,Time,Species,Source,pdf,href formula,href,Case Number,Case Number.1,Unnamed: 21,Unnamed: 22
count,7090,7072,7040,6603,6523,6507,6872,6512,4096,7054,...,3563,3959,7070,6799,6794,6796,6798,6797,1,2
unique,6098,14,253,948,4634,1612,5804,11,178,4200,...,478,1748,5415,6789,6784,6776,6777,6775,1,2
top,1957,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,17,FATAL,...,Afternoon,White shark,"K. McMurray, TrackingSharks.com",1907.10.16.R-HongKong.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2021.07.23,2012.09.02.b,stopped here,Teramo
freq,11,5239,2581,1192,191,1152,679,5685,174,863,...,215,194,131,2,2,4,2,2,1,1

In [26]:
df.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='object')

In [27]:
df["Year"].unique()

array([2026., 2025., 2024., 2023., 2022., 2021., 2020., 2019., 2018.,
       2017.,   nan, 2016., 2015., 2014., 2013., 2012., 2011., 2010.,
       2009., 2008., 2007., 2006., 2005., 2004., 2003., 2002., 2001.,
       2000., 1999., 1998., 1997., 1996., 1995., 1984., 1994., 1993.,
       1992., 1991., 1990., 1989., 1969., 1988., 1987., 1986., 1985.,
       1983., 1982., 1981., 1980., 1979., 1978., 1977., 1976., 1975.,
       1974., 1973., 1972., 1971., 1970., 1968., 1967., 1966., 1965.,
       1964., 1963., 1962., 1961., 1960., 1959., 1958., 1957., 1956.,
       1955., 1954., 1953., 1952., 1951., 1950., 1949., 1948., 1848.,
       1947., 1946., 1945., 1944., 1943., 1942., 1941., 1940., 1939.,
       1938., 1937., 1936., 1935., 1934., 1933., 1932., 1931., 1930.,
       1929., 1928., 1927., 1926., 1925., 1924., 1923., 1922., 1921.,
       1920., 1919., 1918., 1917., 1916., 1915., 1914., 1913., 1912.,
       1911., 1910., 1909., 1908., 1907., 1906., 1905., 1904., 1903.,
       1902., 1901., 1900., 1899., 1898., 1897., 1896., 1895., 1894.,
       1893., 1892., 1891., 1890., 1889., 1888., 1887., 1886., 1885.,
       1884., 1883., 1882., 1881., 1880., 1879., 1878., 1877., 1876.,
       1875., 1874., 1873., 1872., 1871., 1870., 1869., 1868., 1867.,
       1866., 1865., 1864., 1863., 1862., 1861., 1860., 1859., 1858.,
       1857., 1856., 1855., 1853., 1852., 1851., 1850., 1849., 1847.,
       1846., 1845., 1844., 1842., 1841., 1840., 1839., 1837., 1836.,
       1835., 1834., 1832., 1831., 1830., 1829., 1828., 1827., 1826.,
       1825., 1823., 1822., 1819., 1818., 1817., 1816., 1815., 1812.,
       1811., 1810., 1808., 1807., 1805., 1804., 1803., 1802., 1801.,
       1800., 1797., 1792., 1791., 1788., 1787., 1786., 1785., 1784.,
       1783., 1780., 1779., 1776., 1771., 1767., 1764., 1758., 1753.,
       1751., 1749., 1755., 1748., 1742., 1738., 1733., 1723., 1721.,
       1703., 1700., 1642., 1691., 1640., 1638., 1637., 1617., 1595.,
       1580., 1555., 1554., 1543., 1518., 1500., 1000.,   77.,    5.,
          0.])

In [28]:
df["Type"].unique()

array(['Unprovoked', 'Questionable', 'UNprovoked', 'Provoked',
       'unprovoked', ' Provoked', 'Watercraft', 'Sea Disaster', nan, '?',
       'Unconfirmed', 'Unverified', 'Invalid', 'Under investigation',
       'Boat'], dtype=object)

In [29]:
df["Country"].unique()

array(['Australia', 'USA', 'Maldives', 'Bahamas', 'New Caledonia',
       'Cayman Islands', 'Brazil', 'US Virgin Islands', 'Mozambique',
       'French Polynesia', 'Samoa', 'Columbia', 'Costa Rica',
       'Puerto Rico', 'Spain', 'Canary Islands', 'South Africa',
       'Vanuatu', 'Jamaica', 'Israel', 'Mexico', 'Philippines',
       'Turks and Caicos', 'Egypt', 'Thailand', 'New Zealand', 'Hawaii',
       'Honduras', 'Indonesia', 'Morocco', 'Belize', 'Maldive Islands',
       'Tobago', 'AUSTRALIA', 'INDIA', 'TRINIDAD', 'BAHAMAS',
       'SOUTH AFRICA', 'MEXICO', 'NEW ZEALAND', 'EGYPT', 'BELIZE',
       'PHILIPPINES', 'Coral Sea', 'SPAIN', 'PORTUGAL', 'SAMOA',
       'COLOMBIA', 'ECUADOR', 'FRENCH POLYNESIA', 'NEW CALEDONIA',
       'TURKS and CaICOS', 'CUBA', 'BRAZIL', 'SEYCHELLES', 'ARGENTINA',
       'FIJI', 'MeXICO', 'ENGLAND', 'JAPAN', 'INDONESIA', 'JAMAICA',
       'MALDIVES', 'THAILAND', 'COLUMBIA', 'COSTA RICA',
       'British Overseas Territory', 'CANADA', 'JORDAN',
       'ST KITTS / NEVIS', 'ST MARTIN', 'PAPUA NEW GUINEA',
       'REUNION ISLAND', 'ISRAEL', 'CHINA', 'IRELAND', 'ITALY',
       'MALAYSIA', 'LIBYA', nan, 'MAURITIUS', 'SOLOMON ISLANDS',
       'ST HELENA, British overseas territory', 'COMOROS', 'REUNION',
       'UNITED KINGDOM', 'UNITED ARAB EMIRATES', 'CAPE VERDE', 'Fiji',
       'DOMINICAN REPUBLIC', 'CAYMAN ISLANDS', 'ARUBA', 'MOZAMBIQUE',
       'PUERTO RICO', 'ATLANTIC OCEAN', 'GREECE', 'ST. MARTIN', 'FRANCE',
       'TRINIDAD & TOBAGO', 'KIRIBATI', 'DIEGO GARCIA', 'TAIWAN',
       'PALESTINIAN TERRITORIES', 'GUAM', 'NIGERIA', 'TONGA', 'SCOTLAND',
       'CROATIA', 'SAUDI ARABIA', 'CHILE', 'ANTIGUA', 'KENYA', 'RUSSIA',
       'TURKS & CAICOS', 'UNITED ARAB EMIRATES (UAE)', 'AZORES',
       'SOUTH KOREA', 'MALTA', 'VIETNAM', 'MADAGASCAR', 'PANAMA',
       'SOMALIA', 'NEVIS', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL',
       'YEMEN', 'GULF OF ADEN', 'Sierra Leone', 'ST. MAARTIN',
       'GRAND CAYMAN', 'Seychelles', 'LIBERIA', 'VANUATU', 'MEXICO ',
       'HONDURAS', 'VENEZUELA', 'SRI LANKA', ' TONGA', 'URUGUAY',
       'MICRONESIA', 'CARIBBEAN SEA', 'OKINAWA', 'TANZANIA',
       'MARSHALL ISLANDS', 'EGYPT / ISRAEL', 'NORTHERN ARABIAN SEA',
       'HONG KONG', 'EL SALVADOR', 'ANGOLA', 'BERMUDA', 'MONTENEGRO',
       'IRAN', 'TUNISIA', 'NAMIBIA', 'NORTH ATLANTIC OCEAN',
       'SOUTH CHINA SEA', 'BANGLADESH', 'PALAU', 'WESTERN SAMOA',
       'PACIFIC OCEAN ', 'BRITISH ISLES', 'GRENADA', 'IRAQ', 'TURKEY',
       'SINGAPORE', 'NEW BRITAIN', 'SUDAN', 'JOHNSTON ISLAND',
       'SOUTH PACIFIC OCEAN', 'NEW GUINEA', 'RED SEA',
       'NORTH PACIFIC OCEAN', 'FEDERATED STATES OF MICRONESIA',
       'MID ATLANTIC OCEAN', 'ADMIRALTY ISLANDS', 'BRITISH WEST INDIES',
       'SOUTH ATLANTIC OCEAN', 'PERSIAN GULF', 'RED SEA / INDIAN OCEAN',
       'PACIFIC OCEAN', 'NORTH SEA', 'NICARAGUA ', 'MALDIVE ISLANDS',
       'AMERICAN SAMOA', 'ANDAMAN / NICOBAR ISLANDAS', 'GABON', 'MAYOTTE',
       'NORTH ATLANTIC OCEAN ', 'THE BALKANS', 'SUDAN?', 'MARTINIQUE',
       'INDIAN OCEAN', 'GUATEMALA', 'NETHERLANDS ANTILLES',
       'NORTHERN MARIANA ISLANDS', 'IRAN / IRAQ', 'JAVA', 'SIERRA LEONE',
       ' PHILIPPINES', 'NICARAGUA', 'CENTRAL PACIFIC',
       'SOLOMON ISLANDS / VANUATU', 'SOUTHWEST PACIFIC OCEAN',
       'BAY OF BENGAL', 'MID-PACIFC OCEAN', 'SLOVENIA', 'CURACAO',
       'ICELAND', 'ITALY / CROATIA', 'BARBADOS', 'MONACO', 'GUYANA',
       'HAITI', 'SAN DOMINGO', 'KUWAIT', 'YEMEN ', 'FALKLAND ISLANDS',
       'CRETE', 'CYPRUS', 'EGYPT ', 'WEST INDIES', 'BURMA', 'LEBANON',
       'PARAGUAY', 'BRITISH NEW GUINEA', 'CEYLON', 'OCEAN', 'GEORGIA',
       'SYRIA', 'TUVALU', 'INDIAN OCEAN?', 'GUINEA', 'ANDAMAN ISLANDS',
       'EQUATORIAL GUINEA / CAMEROON', 'COOK ISLANDS', 'TOBAGO', 'PERU',
       'AFRICA', 'ALGERIA', 'Coast of AFRICA', 'TASMAN SEA', 'GHANA',
       'GREENLAND', 'MEDITERRANEAN SEA', 'SWEDEN', 'ROATAN',
       'Between PORTUGAL & INDIA', 'DJIBOUTI', 'BAHREIN', 'KOREA',
       'RED SEA?', 'ASIA?', 'CEYLON (SRI LANKA)'], dtype=object)

In [32]:
df["Location"].unique()

array(['Kennedy Shoal', 'Assateague State Park',
       'Horseshoe Reef  Rottnest Island', ..., 'Ocracoke Inlet',
       'Panama Bay 8ºN, 79ºW', 'Below the English fort, Trincomalee'],
      shape=(4635,), dtype=object)

In [33]:
df["Activity"].unique()

array(['Spearfishing', 'Surfing', 'Skindiving', ...,
       'Crew swimming alongside their anchored ship',
       '4 men were bathing', 'Wreck of  large double sailing canoe'],
      shape=(1613,), dtype=object)

In [36]:
df["Age"].unique()
#df["Age"].nunique()

array(['39', '?', '38', '16', '22', '30+', "50's", '55', '13', '11', '27',
       '12', '26', '56', '24', '25', '61', '40', '14', '50+', '54', '48',
       '57', '8', '63', '9', '19', '7', '85', '69', '18', '66', '21',
       '37', '20', '42', '45', '30', '40+', '29', '35', '58', '17', '36',
       '23', '28', '60+', '68', '33', '15', '41', '43', 'Middle age',
       '49', '46', '65', '64', nan, '32', '10', '62', '52', '44', '47',
       '59', '50', '34', '30s', '20/30', '20s', '77', '60', '!2', '73',
       '50s', '67', '6', '53', '51', '31', '40s', 'teen', 'Teen', 'M',
       '!6', '!!', '71', '75', '45 and 15', '70', '4', '28 & 22',
       '22, 57, 31', '60s', "20's", '74', '9 & 60', 'a minor', '3', '82',
       '40?', '72', '18 months', '28 & 26', '5', '86', '18 or 20',
       '12 or 13', '46 & 34', '28, 23 & 30', 'Teens', '36 & 26',
       '8 or 10', '84', '\xa0 ', ' ', '30 or 36', '6½', '21 & ?',
       '33 or 37', 'mid-30s', '23 & 20', ' 30', '7      &    31', ' 28',
       '20?', "60's", '32 & 30', '16 to 18', '87', 'Elderly', 'mid-20s',
       'Ca. 33', '74 ', '45 ', '21 or 26', '20 ', '>50', '18 to 22',
       'adult', '9 & 12', '? & 19', '9 months', '25 to 35', '23 & 26',
       '1', '(adult)', '33 & 37', '25 or 28', '37, 67, 35, 27,  ? & 27',
       '21, 34,24 & 35', '30 & 32', '50 & 30', '17 & 35', 'X',
       '"middle-age"', '13 or 18', '34 & 19', '33 & 26', '2 to 3 months',
       'MAKE LINE GREEN', ' 43', '81', '"young"', '7 or 8', '78',
       '17 & 16', 'F', 'Both 11', '9 or 10', 'young', '36 & 23', '  ',
       'A.M.', '?    &   14', '10 or 12', '31 or 33', '2½', '13 or 14'],
      dtype=object)

In [37]:
df["Sex"].unique()

array(['M', 'F', 'M ', '?', 'F ', nan, ' M', 'm', 'lli', 'M x 2', 'N',
       '.'], dtype=object)

In [38]:
df["Injury"].unique()

array(['Bite wounds to the head', 'Bite wound to the hand',
       'Severe injuries both legs', ..., 'FATAL, leg stripped of flesh  ',
       'FATAL, knocked overboard by tail of shark & carried off by shark ',
       'FATAL. "Shark bit him in half, carrying away the lower extremities" '],
      shape=(4201,), dtype=object)

In [40]:
df["Fatal Y/N"].unique()

array(['Y', 'N', 'F', 'M', nan, 'n', 'Nq', 'UNKNOWN', '2017', 'Y x 2',
       ' N', 'N ', 'y'], dtype=object)

In [41]:
df["Time"].unique()

array(['1100hrs', '?', '1000hrs', '1730hrs', '1715hrs', '1015hrs',
       '0800hrs', '0815hrs', '1815hrs', '0830hrs', '1145hrs', '1820hrs',
       '1620hrs', '0540hrs', '1628hrs', '1200hrs', '1630hrs', '0630hrs',
       '1745hrs', 'Not stated', 'Mid afternoon', '1800hrs', '1823 hrs',
       '1330hrs', '0100hrs', '0930hrs', '1524hrs', '0730hrs', '1300hrs',
       '1055 hrs', '1130hrs', 'PM', '1150hrs', '1500hrs', '1600',
       '1615 hrs', '1210hrs', '1211 hrs', '1400hrs', 'pm', '0945hrs',
       '1430hrs', '1210 hrs', '1340hrs', 'Unknown', '1503hrs', '1830hrs',
       '1645 hrs', '1711hrs', '1600hrs', '1615hr', '1710hr', '1637hr',
       'AM', '1600hr', '1735hrs', '1115hrs', '1118hrs', '1615hrs',
       '1100hr', 'after 1200hr', '1400hr', '15.5', '13h15', '9h', '1300',
       '14h', '15h30', '13h30', '9h15', 'Not advised', '13h40', '12h30',
       '16h00', nan, '11h30', '06h30', '20h00', '13h00', '11h12', '16h30',
       '15h00', '02h00', '09h15', 'Early Morning', '16h32', '11h00',
       'Morning', '10h30', '13h20', '14h00', '09h00', '10h20', '15h05',
       '17h00', '15h45', '07h45', '10h40', '07h50', '01h00', '10h00',
       'Afternoon', '19h30', 'Evening', '17h50', '09h30', '08h45',
       '"Midday"', '16h25', '13h55', '13h50', '17h20', '13h45', '10h10',
       '14h35', 'Night', '1500h ', '19h15', '11h20', '07h15', '07h00',
       '18h00', '08h00', '14h20', '17h30', '07h20', '14h50', '-16h30',
       '12h00', '17h17', '11h15', '19h00', '07h53', '16h10', '11h17',
       '17h45', '10jh45', 'Early  morning', '13h12', '07h30', '11hoo',
       '11h43', '10h15', '14h09', '12h15', '19h12', '15h20', '16h40',
       '11h24', '12h50', '07h31', '14h45', '1040hrs', '19h20', 'Dusk',
       '11h45', '06h40', '`17h00', '07h51', '11h46', '20h30', '12h23',
       '07h07', '16h39', '15h57', '14h30', '16h45', '10j30', '08h15',
       '08h56', '15h40', '18h30', '800', '07h58', '17h40', '09h00-10h00',
       '17h10', '09h36', '08h40', '06h00', 'Sunset', '10h45', '1415',
       '14h00-15h00', '14h15', '09h08', '15h59', '08h30', '12h20',
       '10h50', 'Midday', '09h40', '14h33', '12h58', '"Evening"', '16h15',
       '23h00', '06h50', '12h45', '11h55', '22h20', '08h48', '16h21',
       '16h26', '18h45', '03h00', '06h15', 'Before 10h00', '06h45',
       'Early afternoon', '06h55', '13h42', '09h29', '10h47', '14h11',
       '15h35', '14h40', '14h00  -15h00', 'Late afternoon', '16h50',
       '21h50', '17h35', '19h00, Dusk', '15h01', '1000', '23h30', '10h44',
       '13h19', 'Shortly before 12h00', '17h34', '08h50', '09h50', '9h00',
       '10h43', 'After noon', '15h15', '19h05', '14h30 / 15h30', '22h00',
       '16h20', '14h34', '15h25', '14h55', '17h46', 'Morning ', '15h49',
       'Midnight', '09h30 / 10h00', '18h15', '04h00', '10h25',
       '10h45-11h15', '15h52', '19h45', '12h10', '18h05', '11h41',
       '12h25', '17h51', '16h12', '09h45', '05h00', '03h30',
       'Sometime between 06h00 & 08hoo', '16h18', '11h10',
       '07h00 - 08h00', '18h15-18h30', '17h01', '09h57', '08h20', '17h58',
       '15h19', '10h55', '15h55', '12h40', '16h05', '14h10', '13h24',
       '09h00 - 09h30', '0830', '11h40', '08h10', '15h56',
       'Just before noon', '07h56', '16h35', '09h05', '19h28', '12h38',
       '05h50', '15h50', '11h05', 'Early morning', 'Dawn', '05h45',
       '13h25', '13h26', '09h11', '18h20', '13h51', 'A.M.', '08h05',
       '10h35', '15h44', '21h00', 'Lunchtime', '15j45', '09h35', '10h27',
       '10h16', '0500', 'Before 07h00', '09h20', '10h00 -- 11h00',
       '12h05', '14h21', '18h50', '15h53', '"Just before 11h00"',
       '11h115', '20h15', '12h39', '07h05', '  ', '13h05', 'N', '11h50',
       'Just before sundown', '17h55', '22h30', '17h15', '11h30 ',
       '06h10', 'Between 05h00 and 08h00', '07h08', '17h00 or 17h40',
       '>08h00', '--', '12h02', '12h55', '16h14', '17h11', '00h30',
       '14h37', '10h07', '13h53', '13h23', 'Just after 12h00', '02h30',
       '11h56', ' ', 'Shortly after midnight', '14h25', '13h345', '\xa0 ',
       '06h47', '09h00 -10h00', '20h45 (Sunset)', 'Late morning', 'P.M.',
       '18h40', '13h14', '13h06', 'Shortly before 13h00', '12h34',
       '11h53', '8:04 pm', '12h46', '12h48', '17h42', '12h35',
       'Possibly same incident as 2000.08.21', 'After Dusk', '11h57',
       'Noon', '11h25', '18h25', '10h28', '14h16', '09h55',
       '2 hours after Opperman', '09h30 ', 'Mid morning', '11h48',
       '11h00 / 11h30', '07h19', '13h37', '11h06', '"Night"', '18h30?',
       '11h58', '11h51', '18h12', '07h10', '07h40', '12h33',
       '30 minutes after 1992.07.08.a', '>06h45', '15h06', '12h54',
       'Between 06h00 & 07h20', '16h55', '05h40', '<07h30', '21h30',
       '17h00 Sunset', 'Nightfall', 'X', '08h57', '18h30 (Sunset)',
       '06j00', '08h35', '10h22', '02h45', 'Prior to 10h37', 'Daybreak',
       '18h10', '>12h00', 'Mid-morning', '08h55', '16h30 or 18h00',
       'Just before dawn', ' 14h00', 'Daytime', 'Dark', '10h00 / 11h00',
       '"After lunch"', '07h32', '15h00 or 15h45', '>17h00',
       '19h00 / 20h00', '12h45 / 13h45', '14h00 - 15h00', 'night',
       '03h45 - 04h00', '13h10', '09h30 / 15h30', '08h00 / 09h30',
       '19h35', '12h00 to 14h00', '13h35', 'Late night', '01h32',
       '10h30 or 13h30', '16h23', '15h00j', 'Midday.', '"After dark"',
       '10h00 or 14h00', '19h10', '2 hrs before sunset', '18h15 to 21h30',
       '1500', '"shortly before dusk"', '>17h30', '>14h30',
       'Between 11h00 & 12h00', 'After 04h00',
       '11h01 -time of ship sinking', 'Ship aban-doned at 03h10', '19h55',
       'After dusk',
       'FATAL  (Wire netting installed at local beaches after this incident.)',
       '01h30', 'After midnight', 'Late afternon', '05h30', '08h58',
       '"Early evening"', 'Late Afternoon', '   ', 'Before daybreak',
       'dusk', 'Before 10h30', '06h00 -- 07h00', '01h50', '17h00-18h00',
       '19h00-20h00'], dtype=object)

In [10]:
df["Type"].value_counts(dropna=False)

Type
Unprovoked             5239
Provoked                642
Invalid                 552
Watercraft              355
Sea Disaster            242
Questionable             27
NaN                      18
Boat                      7
 Provoked                 2
UNprovoked                1
unprovoked                1
?                         1
Unconfirmed               1
Unverified                1
Under investigation       1
Name: count, dtype: int64

In [11]:

df["Country"].value_counts().head(20)

Country
USA                 2581
AUSTRALIA           1482
SOUTH AFRICA         597
NEW ZEALAND          144
PAPUA NEW GUINEA     136
BAHAMAS              136
BRAZIL               122
MEXICO               103
ITALY                 72
FIJI                  67
NEW CALEDONIA         65
PHILIPPINES           63
REUNION               60
EGYPT                 49
CUBA                  49
Australia             49
SPAIN                 46
MOZAMBIQUE            46
INDIA                 41
FRENCH POLYNESIA      37
Name: count, dtype: int64

In [7]:
sorted(df["Country"].dropna().unique())

[' PHILIPPINES',
 ' TONGA',
 'ADMIRALTY ISLANDS',
 'AFRICA',
 'ALGERIA',
 'AMERICAN SAMOA',
 'ANDAMAN / NICOBAR ISLANDAS',
 'ANDAMAN ISLANDS',
 'ANGOLA',
 'ANTIGUA',
 'ARGENTINA',
 'ARUBA',
 'ASIA?',
 'ATLANTIC OCEAN',
 'AUSTRALIA',
 'AZORES',
 'Australia',
 'BAHAMAS',
 'BAHREIN',
 'BANGLADESH',
 'BARBADOS',
 'BAY OF BENGAL',
 'BELIZE',
 'BERMUDA',
 'BRAZIL',
 'BRITISH ISLES',
 'BRITISH NEW GUINEA',
 'BRITISH VIRGIN ISLANDS',
 'BRITISH WEST INDIES',
 'BURMA',
 'Bahamas',
 'Belize',
 'Between PORTUGAL & INDIA',
 'Brazil',
 'British Overseas Territory',
 'CANADA',
 'CAPE VERDE',
 'CARIBBEAN SEA',
 'CAYMAN ISLANDS',
 'CENTRAL PACIFIC',
 'CEYLON',
 'CEYLON (SRI LANKA)',
 'CHILE',
 'CHINA',
 'COLOMBIA',
 'COLUMBIA',
 'COMOROS',
 'COOK ISLANDS',
 'COSTA RICA',
 'CRETE',
 'CROATIA',
 'CUBA',
 'CURACAO',
 'CYPRUS',
 'Canary Islands',
 'Cayman Islands',
 'Coast of AFRICA',
 'Columbia',
 'Coral Sea',
 'Costa Rica',
 'DIEGO GARCIA',
 'DJIBOUTI',
 'DOMINICAN REPUBLIC',
 'ECUADOR',
 'EGYPT',
 'EGYPT ',
 'EGYPT / ISRAEL',
 'EL SALVADOR',
 'ENGLAND',
 'EQUATORIAL GUINEA / CAMEROON',
 'Egypt',
 'FALKLAND ISLANDS',
 'FEDERATED STATES OF MICRONESIA',
 'FIJI',
 'FRANCE',
 'FRENCH POLYNESIA',
 'Fiji',
 'French Polynesia',
 'GABON',
 'GEORGIA',
 'GHANA',
 'GRAND CAYMAN',
 'GREECE',
 'GREENLAND',
 'GRENADA',
 'GUAM',
 'GUATEMALA',
 'GUINEA',
 'GULF OF ADEN',
 'GUYANA',
 'HAITI',
 'HONDURAS',
 'HONG KONG',
 'Hawaii',
 'Honduras',
 'ICELAND',
 'INDIA',
 'INDIAN OCEAN',
 'INDIAN OCEAN?',
 'INDONESIA',
 'IRAN',
 'IRAN / IRAQ',
 'IRAQ',
 'IRELAND',
 'ISRAEL',
 'ITALY',
 'ITALY / CROATIA',
 'Indonesia',
 'Israel',
 'JAMAICA',
 'JAPAN',
 'JAVA',
 'JOHNSTON ISLAND',
 'JORDAN',
 'Jamaica',
 'KENYA',
 'KIRIBATI',
 'KOREA',
 'KUWAIT',
 'LEBANON',
 'LIBERIA',
 'LIBYA',
 'MADAGASCAR',
 'MALAYSIA',
 'MALDIVE ISLANDS',
 'MALDIVES',
 'MALTA',
 'MARSHALL ISLANDS',
 'MARTINIQUE',
 'MAURITIUS',
 'MAYOTTE',
 'MEDITERRANEAN SEA',
 'MEXICO',
 'MEXICO ',
 'MICRONESIA',
 'MID ATLANTIC OCEAN',
 'MID-PACIFC OCEAN',
 'MONACO',
 'MONTENEGRO',
 'MOZAMBIQUE',
 'Maldive Islands',
 'Maldives',
 'MeXICO',
 'Mexico',
 'Morocco',
 'Mozambique',
 'NAMIBIA',
 'NETHERLANDS ANTILLES',
 'NEVIS',
 'NEW BRITAIN',
 'NEW CALEDONIA',
 'NEW GUINEA',
 'NEW ZEALAND',
 'NICARAGUA',
 'NICARAGUA ',
 'NIGERIA',
 'NORTH ATLANTIC OCEAN',
 'NORTH ATLANTIC OCEAN ',
 'NORTH PACIFIC OCEAN',
 'NORTH SEA',
 'NORTHERN ARABIAN SEA',
 'NORTHERN MARIANA ISLANDS',
 'NORWAY',
 'New Caledonia',
 'New Zealand',
 'OCEAN',
 'OKINAWA',
 'PACIFIC OCEAN',
 'PACIFIC OCEAN ',
 'PALAU',
 'PALESTINIAN TERRITORIES',
 'PANAMA',
 'PAPUA NEW GUINEA',
 'PARAGUAY',
 'PERSIAN GULF',
 'PERU',
 'PHILIPPINES',
 'PORTUGAL',
 'PUERTO RICO',
 'Philippines',
 'Puerto Rico',
 'RED SEA',
 'RED SEA / INDIAN OCEAN',
 'RED SEA?',
 'REUNION',
 'REUNION ISLAND',
 'ROATAN',
 'RUSSIA',
 'SAMOA',
 'SAN DOMINGO',
 'SAUDI ARABIA',
 'SCOTLAND',
 'SENEGAL',
 'SEYCHELLES',
 'SIERRA LEONE',
 'SINGAPORE',
 'SLOVENIA',
 'SOLOMON ISLANDS',
 'SOLOMON ISLANDS / VANUATU',
 'SOMALIA',
 'SOUTH AFRICA',
 'SOUTH ATLANTIC OCEAN',
 'SOUTH CHINA SEA',
 'SOUTH KOREA',
 'SOUTH PACIFIC OCEAN',
 'SOUTHWEST PACIFIC OCEAN',
 'SPAIN',
 'SRI LANKA',
 'ST HELENA, British overseas territory',
 'ST KITTS / NEVIS',
 'ST MARTIN',
 'ST. MAARTIN',
 'ST. MARTIN',
 'SUDAN',
 'SUDAN?',
 'SWEDEN',
 'SYRIA',
 'Samoa',
 'Seychelles',
 'Sierra Leone',
 'South Africa',
 'Spain',
 'TAIWAN',
 'TANZANIA',
 'TASMAN SEA',
 'THAILAND',
 'THE BALKANS',
 'TOBAGO',
 'TONGA',
 'TRINIDAD',
 'TRINIDAD & TOBAGO',
 'TUNISIA',
 'TURKEY',
 'TURKS & CAICOS',
 'TURKS and CaICOS',
 'TUVALU',
 'Thailand',
 'Tobago',
 'Turks and Caicos',
 'UNITED ARAB EMIRATES',
 'UNITED ARAB EMIRATES (UAE)',
 'UNITED KINGDOM',
 'URUGUAY',
 'US Virgin Islands',
 'USA',
 'VANUATU',
 'VENEZUELA',
 'VIETNAM',
 'Vanuatu',
 'WEST INDIES',
 'WESTERN SAMOA',
 'YEMEN',
 'YEMEN ']

In [12]:
df["Activity"].value_counts().head(20)

Activity
Surfing            1152
Swimming           1016
Fishing             494
Spearfishing        392
Wading              178
Bathing             164
Diving              151
Snorkeling          135
Standing            113
Scuba diving         84
Body boarding        63
Body surfing         50
Swimming             47
Boogie boarding      42
Kayaking             40
Treading water       33
Free diving          33
Pearl diving         32
Fell overboard       32
Windsurfing          20
Name: count, dtype: int64

In [13]:
df["Fatal Y/N"].value_counts(dropna=False)

Fatal Y/N
N          4944
Y          1493
NaN         561
UNKNOWN      71
 N            7
F             5
M             3
n             1
Nq            1
2017          1
Y x 2         1
N             1
y             1
Name: count, dtype: int64

In [14]:
df["Sex"].value_counts(dropna=False)

Sex
M        5685
F         811
NaN       578
M           5
?           2
F           2
N           2
 M          1
m           1
lli         1
M x 2       1
.           1
Name: count, dtype: int64

In [15]:
df["Year"].value_counts().sort_index()

Year
0.0       129
5.0         1
77.0        1
1000.0      1
1500.0      1
         ...
2022.0     98
2023.0    109
2024.0     52
2025.0     68
2026.0     27
Name: count, Length: 261, dtype: int64

In [16]:
df["State"].value_counts().head(20)

State
Florida                  1192
New South Wales           522
Queensland                355
Hawaii                    345
California                328
Western Australia         245
KwaZulu-Natal             219
Western Cape Province     197
South Carolina            175
Eastern Cape Province     168
South Australia           122
North Carolina            119
Victoria                   96
Texas                      83
Pernambuco                 80
North Island               76
Torres Strait              70
New Jersey                 56
New York                   45
Tasmania                   45
Name: count, dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)